== edea Assignment 2 : Metropolis

=== Bearbeitet von

* Thierry Odermatt

=== Abgabe

* Dienstag, 10.1.2023, 8:00 Uhr

* Die Abgabe erfolgt durch einen `Push` auf den `main`-Branch Ihres GitHub-Repositories.
* Die Wireframes von Metropolis 2.0 sind auf oberster Hierarchie im File "metropolis_2_Odermatt.bpmr" zu finden.

=== Initiale Schritte
[circle]
* Tragen Sie ihren Namen unter "Bearbeitet von" ein.
* Pushen Sie diese Änderung am besten sofort ins Git-Repository (z.B. via "Git -> Commit… -> Commit&Push")


=== Die Aufgabe: Desktop Applikation zur Verwaltung von Städte-Informationen

Im Zentrum steht die Verwaltung von Gemeinden und Städten mit mehr als 500 Einwohnern. Weltweit sind dies ca. 200'000. Dafür ist die Entwicklung von mindestens zwei Explorern und zwei Editoren notwendig (jeweils für Städte und Länder)

Dieses Assignment entspricht einer typischen Situation, in der sich Software-Firmen häufig befinden. Es soll in sehr kurzer Zeit eine erste Version einer Geschäftsapplikation umgesetzt werden, die bereits eingesetzt werden kann und damit einen Nutzen beim Auftraggeber erzeugt. Auf dieser Basis wird dann ein längerfristiges Projekt definiert, bei dem die Geschäftsapplikation weiter optimiert wird.

Dementsprechend besteht das Assignment aus drei Teilen
[circle]
* _Entwurf_ der Applikation, so dass die Applikation _mit möglichst geringem Aufwand_ technisch umsetzbar ist. Normalerweise hat dieser Entwurf Schwächen im Bereich der Usability.
** Dieser Entwurf muss nicht weiter dokumentiert werden (kein Wireframe muss abgegeben werden)
** Empfehlung: suchen Sie in einem Team von 2-3 Personen nach der einfachsten Lösung
* _Implementierung_ von `Metropolis`
** basierend auf den Beispielen und insbesondere den `xtracted`-Packages aus `module08` und `module09`
** die beiden Explorer müssen LazyLoading, Sortieren und Filtern unterstützen
** die Editoren unterstützen Mehrsprachigkeit, Input-Validierung und Undo/Redo
** das ist eine Einzelarbeit
* _Entwurf_ der _nächsten_ Applikations-Version.
** Wie sieht das aus Benutzersicht optimale Interaktions-Konzept für `Metropolis 2.0` aus?
** Wie ist das optimale Zusammenspiel zwischen den beiden Explorern?
** Was soll passieren, wenn im `CountryExplorer` ein Land selektiert wird?
** Wann "erscheinen" die Editoren?
** Wie kann am besten bei einer Stadt das Land eingetragen werden?
** Wie kann die Datenkonsistenz sichergestellt werden, z.B. wenn bei einem Land die Hauptstadt eingetragen wird?
** Wann werden die Datenänderungen in einem Editor auch in den entsprechenden Explorern angezeigt?
** Wie wird visualisiert welche Datensätze verändert und noch nicht gespeichert wurden?
** dieser Teil der Aufgabe wird idealerweise in einem kleinen Team (zwei bis drei Personen) bearbeitet
** Dokumentieren Sie ihren Entwurf als Balsamiq-WireFrame


=== Anforderungen
[circle]
* Gewünschte Funktionalität
** 2 Explorer, jeweils mit Lazy-Loading aus der lokalen Datenbank `metropolisDB`, Sortier- und Filter-Möglichkeiten auf mindestens vier Spalten
*** Implementierung basiert auf den Beispielen aus `module08`
*** `CityExplorer` für die ca. 200'000 Städte und Gemeinden
*** `CountryExplorer` für die ca. 250 Länder
** 2 Editoren, jeweils mit Header-Bereich und Formular-Bereich
*** Implementierung basiert auf den Beispielen aus `module09`
*** `CityEditor` muss auf jeden Fall das Feld für den `COUNTRY_CODE` enthalten
*** `CountryEditor` muss auf jeden Fall das Feld für `CAPITAL` enthalten
** neue Städte/Länder können angelegt, bestehende aus der Datenbank gelöscht werden
** die Explorer und Editoren müssen jeweils separat, mit einer eigenen Demo-Applikation gestartet werden können
** `Metropolis` verbindet die Explorer und Editoren zu einer Gesamtapplikation
*** Selektion einer Stadt im `CityExplorer`
**** "öffnet" den `CityEditor`
**** zeigt die Länder-Information in geeigneter Weise im `CountryExplorer`/`CountryEditor` an
*** Selektion eines Landes im `CountryExplorer`
**** öffnet den `CountryEditor`
**** zeigt die Information der Hauptstadt in geeigneter Weise im `CityExplorer`/`CityEditor` an
**** zeigt die Städte dieses Landes in geeigneter Weise im `CityExplorer` an
** _Wichtiger Hinweis_: Es sind Veränderungen und Erweiterungen in den `xtracted`-Packages notwendig. Diese können nicht unverändert übernommen werden.
* Die Implementierungssprache für die gesamte Applikation ist Kotlin
* Das UI ist mit Compose Desktop zu entwickeln
* Verwendung von JDBC für die Datenbank-Zugriffe
* Keine Verwendung von externen Libraries, die nicht bereits im Unterricht eingesetzt wurden


=== Bewertung
Es können in diesem Assignment maximal 4 Punkte erreicht werden.
[circle]
* Davon gehen 2 Punkte in die Implementierung von `Metropolis`. Der Fokus liegt dabei, neben der Umsetzung der gewünschten Funktionalität, auf der Code-Qualität.
* Für das Interaction-Design für `Metropolis 2.0` können ebenfalls 2 Punkte erreicht werden.


* 4 Punkte
** Umsetzung der gesamten gewünschten Funktionalität und der oben genannten Grundanforderungen (2 Punkte)
** Das Interaction-Design für `Metropolis 2.0` liegt in Form von Balsamiq-Wireframes vor und zeigt signifikante Verbesserungen gegenüber `Metropolis` (2 Punkte)
** Alle Kriterien für 1 Punkt sind erfüllt
* 1 Punkt
** Umsetzung von `CityExplorer` und `CityEditor`, auf Basis der `xtracted`-Packages aus `module08` und `module09`
** Selektion einer Stadt "öffnet" den entsprechenden Editor
** Änderungen im Editor können in der Datenbank abgespeichert werden
** Neue Städte können angelegt werden
** Bestehende Städte können aus der Datenbank gelöscht werden
* 0 Punkte
** falls kein `CityExplorer` und `CityEditor` implementiert wurde; das Interaction-Design von `Metropolis 2.0` reicht allein nicht für einen Punkt
** falls die Kriterien für einen Punkt nicht erfüllt sind ;-)
** falls eine weitere externe Library ohne Rücksprache verwendet wird
** falls das Projekt nicht kompilierfähig ist
** falls die Applikation direkt beim Aufstarten abstürzt
** für Plagiate



=== Compose Desktop Application
Sie können eine "doppelklickbare" Applikation und einen dazugehörigen Installer generieren lassen.

Dazu in `src/main/kotlin/main.kt` die zu startende Applikation eintragen.

* `./gradlew run` - startet die Applikation (ist die richtige Applikation eingetragen?)
* `./gradlew packageDistributionForCurrentOS` - erzeugt eine doppelklickbare Applikation und einen Installer (siehe  `build/compose/binaries`)